{
 "title": "LibGuardian",
 "time": { "from": "2025-06-10T13:15:14.983Z", "to": "2025-06-10T13:15:20.829Z" },
 "panels": [
  {
   "title": "People in room 101 through time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT \n    timestamp,\n    number_of_people\nFROM \n    people_movements\nWHERE \n    door_id = 1\nORDER BY \n    timestamp ASC;"
    }
   ]
  },
  {
   "title": "People in Room 101",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT \n    timestamp,\n    number_of_people\nFROM \n    people_movements\nWHERE \n    door_id = 1\nORDER BY \n    timestamp ASC;"
    }
   ]
  },
  {
   "title": "People in room 102 through time (simulated)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT \n    timestamp,\n    number_of_people\nFROM \n    people_movements\nWHERE \n    door_id = 2\nORDER BY \n    timestamp ASC;"
    }
   ]
  },
  {
   "title": "People in Room 102 (simulated)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT \n    timestamp,\n    number_of_people\nFROM \n    people_movements\nWHERE \n    door_id = 2\nORDER BY \n    timestamp ASC;"
    }
   ]
  },
  {
   "title": "Actual Noise in Room 101",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT \n    se.readings\nFROM sensor_events se\nJOIN noise_sensors ns ON se.sensor_id = ns.sensor_id\nJOIN sensors s ON se.sensor_id = s.sensor_id\nJOIN rooms r ON s.room_id = r.room_id\nWHERE r.room_id = 1\nORDER BY se.timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Actual Noise in Room 102 (simulated)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT se.readings\nFROM sensor_events se\nJOIN noise_sensors ns ON se.sensor_id = ns.sensor_id;"
    }
   ]
  },
  {
   "title": "Noise in Room 101 through time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT\n    se.timestamp,\n    se.readings\nFROM sensor_events se\nJOIN noise_sensors ns ON se.sensor_id = ns.sensor_id\nJOIN sensors s ON se.sensor_id = s.sensor_id\nJOIN rooms r ON s.room_id = r.room_id\nWHERE r.room_id = 1\nORDER BY se.timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Actual Noise Room 102 (simulated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "LibGuardian",
     "rawSql": "SELECT\n    se.timestamp,\n    se.readings\nFROM sensor_events se\nJOIN noise_sensors ns ON se.sensor_id = ns.sensor_id\nJOIN sensors s ON se.sensor_id = s.sensor_id\nJOIN rooms r ON s.room_id = r.room_id\nWHERE r.room_id = 2\nORDER BY se.timestamp DESC;\n"
    }
   ]
  }
 ]
}